const sample = <T>(items: T[]): T => items[Math.floor(Math.random() * items.length)];

export const turnPrompts = [
	`______: good to the last drop.`,
	`______: kid tested, mother approved.`,
	`______? Bob'll fix it!`,
	`????? Do NOT go here! Found _____ in my fettuccine alfredo!`,
	`A romantic candlelit dinner would be incomplete without ______.`,
	`After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ______.`,
	`But before I kill you, Mr. Bond, I must show you ______.`,
	`Channel 9 is pleased to present its new variety show, "Hey Hey It's ______."`,
	`Click Here for ______!!!`,
	`Hey Reddit! I'm ______. Ask me anything.`,
	`Howdy, neighbor! I couldn't help but notice you struggling with ______. Need a hand?`,
	`I wish I hadn't lost the instruction manual for ______.`,
	`Life was difficult for cavemen before ______.`,
	`TFL apologizes for the delay in train service due to ______.`,
	`This season at Steppenwolf, Samuel Beckett's classic existential play: Waitng for ______.`,
	`What's the new fad diet?`,
	`What's that sound?`,
	`And over here is Picasso's famous painting, "portrait of _______."`,
	`Come with me, and I will show you a world of ______.`,
	`I lost my arm in a ______ accident.`,
	`What killed Old Jim?`,
	`They just enacted a new city bylaw to prevent ______.`,
	`Best dog toys: tennis balls, bones, ______.`,
	`What's way better than the dog park?`,
	`Deadlines are for _________.`,
	`Creativity is a concept lost on people who _________.`,
	`I may be a temperamental artist, but you're a __________.`,
	`It's great to be a creative mind in a workplace full of _________.`,
	`Strategically speaking, the project should _________.`,
	`It was a perfect project until _________.`,
	`Let's forget the feedback for a moment, what if we _________.`,
	`People ask me all the time what the secret is to my creativity, I tell them it's __________.`,
	`No. We don't support ______.`,
	`What's your user hiding from you?`,
	`Pentesting found a _______________ process running on the printer`,
	`_______________ attacks are such a hot exploit right now`,
	`_________ won my vote.`,
	`Ever since the drought, we've had a crippling shortage of _________.`,
	`Forget the tech industry, the next big thing is _________.`,
	`Hands down, NorCal is the best place to find _________.`,
	`I just graduated with a degree in __________.`,
	`I've started a new workout plan that revolves around _________.`,
	`What is a software engineer's best friend?`,
	`Sometimes, all you need is a little bit of ______ to brighten your day.`,
	`My autobiography would be incomplete without a chapter on ______.`,
	`Introducing the newest flavor of ice cream: ______!`,
	`What's the secret ingredient in Grandma's famous cookies?`,
	`If I could have any superpower, it would be ______.`,
	`Forget about the moon landing, the real conspiracy is about ______.`,
	`The latest fashion trend is ______.`,
	`The 8th wonder of the world: ______.`,
	`My go-to karaoke song is ______.`,
	`You haven't lived until you've tried ______.`,
	`The secret to a happy marriage is ______.`,
	`What's the most memorable souvenir you've ever received?`,
	`What's the best part of waking up?`,
	`I've always wanted to try ______, but I'm too scared.`,
	`The best way to spend a lazy Sunday is ______.`,
	`My favorite guilty pleasure is ______.`,
	`If I could only bring one thing to a desert island, it would be ______.`,
	`What's the one thing that can always make you smile?`,
	`The next big technological innovation will be ______.`,
	`You won't believe this, but I just saw ______ at the grocery store.`,
	`My secret to a balanced life is incorporating ______ into my daily routine.`,
	`The future of transportation is clearly _______.`,
	`At the farmer's market, I discovered the wonders of ________.`,
	`The latest self-help book everyone is raving about: 'The Power of ________.'`,
	`The next breakthrough in medical technology: ________.`,
	`The new hit reality show: 'America's Got ________.'`,
	`I can't believe I got the world record for ________!`,
	`The most unexpected combination at the ice cream parlor: ________ and ________.`,
	`My favorite way to unwind after a long day is ________.`,
	`In my alternate universe, the most popular sport is ________.`,
	`______ is the key ingredient to a successful party.`,
	`My most embarrassing moment involved ________.`,
	`When I close my eyes and think of paradise, I see ________.`,
	`The world would be a better place if we all embraced ________.`,
	`The most unconventional pizza topping: ________.`,
	`If I could have any superpower, it would be ________.`,
	`My favorite childhood toy was ________.`,
	`_______: the unsung hero of the kitchen.`,
	`The best thing about living in the future is ________.`,
	`It's always a good time for ________.`
];

export const botPrompts = [
	`I will respond with sarcastic and snarky comebacks as if debating a troll on the internet.`,
	`I will respond with creative haikus.`,
	`I will respond with humorous one-liners in the style of dad jokes.`,
	`I will use only words with double letters (Example: Discretion becomes "DisSecrEtioN")`,
	`I will respond with bizarre conspiracy theories like Alex Jones.`,
	`I will respond with puns and dad jokes.`,
	`I will respond with puns and jokes related to famous movie titles.`,
	`I will respond with quotes from famous philosophers and scholars in a whisper voice.`,
	`I will respond with sarcastic remarks like Chandler Bing from Friends.`,
	`I will respond using cheesy pick-up lines like a smooth talker.`,
	`I will respond with sarcastic comments about mundane topics like a bored reality TV star.`,
	`I will respond using only words that have at least three syllables.`,
	`I will respond with one-liner quotes from famous movie villains.`,
	`I will respond with sarcastic compliments as if talking to a diva.`,
	`I will respond with puns and dad jokes.`,
	`I will add "in bed" to the end of every response, like a fortune cookie.`,
	`I will respond with puns based on various professions.`,
	`I will respond with celebrity impressions in a British accent.`,
	`I will respond using only words that contain the letter "e" at least twice.`,
	`I will respond using only one-syllable words, like a children's book.`,
	`I will respond with sarcastic and cynical comments like a grumpy cat.`,
	`I will respond with puns related to different types of fruit.`,
	`I will respond with random movie quotes as if conducting a business meeting.`,
	`I will respond with sarcastic one-liners like a stand-up comedian.`,
	`I will respond with puns and wordplays onomatopoeia style.`,
	`I will respond using only movie quotes from 007 James Bond films.`,
	`I will respond with puns related to different types of shoes.`,
	`I will respond using only words containing five or more letters.`,
	`I will respond in rhyming couplets like a Shakespearean sonnet.`,
	`I will respond with puns related to bees and their hive.`,
	`I will respond with made up idioms that involve animals.`,
	`I will respond in rhyming couplets like a Dr. Seuss book.`,
	`I will respond with sarcastic affirmations in the style of an over-confident know-it-all.`,
	`I will respond with quotes from famous movies or TV shows.`,
	`I will respond with words that rhyme with the prompt card word.`,
	`I will respond with puns related to food and drink.`,
	`I will respond with puns related to animals.`,
	`I will respond with sarcastic comments as if pretending to be a terrible travel agent.`,
	`I will respond using only words that contain the letter "p".`,
	`I will respond with puns and wordplay related to food and cooking.`,
	`I will respond with puns and dad jokes.`,
	`I will respond with facts that people don't typically know.`,
	`I will respond with sarcastic responses as if talking to a child.`,
	`I will respond with witty one-liners as if I were a stand-up comedian.`,
	`I will respond with random facts about animals.`,
	`I will respond with sarcastic comments in the style of a millennial.`,
	`I will respond with a food-related pun.`,
	`I will respond with sarcastic remarks in the style of a pessimistic teenager.`,
	`I will respond with random historical facts about civilizations from around the world.`,
	`I will respond with tongue twisters that have to be said three times fast.`,
	`I will respond with the most absurd and outrageous conspiracy theories.`,
	`I will respond with puns related to food and cooking.`,
	`I will respond with sarcastic comments.`,
	`I will respond with phrases from popular TV comedies.`,
	`I will respond with lyrics from 80s pop songs.`,
	`I will respond with overly dramatic poetic language.`,
	`I will respond with witty one-liners that rhyme with the prompt.`,
	`I will respond with sarcastic compliments and insults in a British accent.`,
	`I will respond with movie or TV show quotes.`,
	`I will respond with sarcastic and witty comments in the style of a stand-up comedian.`,
	`I will respond with one-word responses that sound like an alien language.`,
	`I will respond with conspiracy theories about the Illuminati.`,
	`I will respond in gibberish and then translate it into Shakespearean language.`,
	`I will respond in rhyming couplets like a Dr. Seuss book.`,
	`I will respond with sarcastic responses using made-up words.`,
	`I will respond in Shakespearean English.`,
	`I will respond with sarcastic and witty remarks in the tone of a sophisticated aristocrat.`,
	`I will respond with sarcastic remarks in the style of Chandler Bing from Friends.`,
	`I will respond with jokes that make light of current world affairs.`,
	`I will respond with math jokes and puns.`,
	`I will respond in the form of a question, like a never-ending conversation.`,
	`I will respond with puns based on animal names, so bear with me.`,
	`I will respond with puns related to food and cooking.`,
	`I will respond starting every sentence with "Not gonna lie".`,
	`I will respond with conspiracy theories about the government using aliens to extract information from humans.`,
	`I will respond with sarcastic and ironic humor, like a stand-up comedian.`,
	`I will respond with conspiracy theories inspired by famous works of fiction.`,
	`I will respond with puns and play on words about cars and vehicles.`,
	`I will respond with bad advice from a know-it-all teenager.`,
	`I will respond with sarcastic compliments.`,
	`I will respond with made-up facts that sound legit but are actually ridiculous.`,
	`I will respond by making everything sound like a conspiracy theory.`,
	`I will respond using only sentences that rhyme with each other in a sing-songy tone.`,
	`I will respond with puns and wordplay based on superhero names.`,
	`I will respond with clever puns in the style of dad jokes.`,
	`I will respond with puns incorporating the names of different alcoholic beverages.`,
	`I will respond by incorporating a famous movie quote into each response.`,
	`I will respond with cheesy pick-up lines as if you're trying to seduce the darkness.`,
	`I will respond with puns and wordplay related to animals.`,
	`I will respond with cheesy pick-up lines.`,
	`I will respond using animal noises and sounds.`,
	`I will respond with puns related to electricity and computing terminology.`,
	`I will respond with a fact only a conspiracy theorist would believe.`,
	`I will respond with puns and dad jokes.`,
	`I will respond with puns and wordplay related to science and chemistry.`,
	`I will respond with phrases commonly used by hipsters.`,
	`I will respond with word puns related to cars and driving.`,
	`I will respond with facts about marine life.`,
	`I will respond with random fun facts about animals.`,
	`I will respond with random facts about animals.`
];

export const alignerPrompts = [
	`The most creative and innovative use of the words wins.`,
	`The answer that uses the most "glamorous" and "exaggerated" language will win in this game.`,
	`The most "innovative" and creative answer will win in this game.`,
	`The answer that best "analyzes" and breaks down the situation will win in this game.`,
	`The most creative analogy to relate "Breed" and "Lemon" wins.`,
	`The player who can make the most creative and entertaining use of puns will win.`,
	`The card that relates to the concept of "long-lasting" wins.`,
	`The card with the most effective defense mechanism wins.`,
	`The most creative and unique use of the word in a sentence wins.`,
	`The person who comes up with the most "punishingly" creative response wins.`,
	`The answer that makes me laugh the most wins the round.`,
	`The answer that best captures the "grandiosity" or size of the concept wins.`,
	`The card that elicits the most heartwarming emotion wins.`,
	`The best interpretation of the word in the given context wins.`,
	`The funniest pairing of cards wins.`,
	`The funniest joke related to "cups" wins this round.`,
	`The answer that best conveys emotion and meaning wins.`,
	`The most creative and original combination of the two words will win in this game.`,
	`The card with the most creative interpretation using "everyday rules" wins.`,
	`The funniest and most energetic combination wins.`,
	`The card that best embodies the heroic spirit wins.`,
	`The player who comes up with the most creative and original sentence using both words wins.`,
	`The most creative and innovative answer will win in this game.`,
	`Whoever presents the most creative use of the word "irrigation" in a sentence wins. Bonus points for incorporating the word "aside" in a clever way.`,
	`The funniest combination of cards wins each round.`,
	`The player with the most creative and unexpected usage of the word "occurring" wins in this game.`,
	`The answer that is the most visually creative and graphic will win in this game.`,
	`The submission with the most creative "organization strategy" wins.`,
	`The funniest and most creative response will win the round.`,
	`The most creative and unique interpretation of the word will win in this game.`,
	`The funniest combination that makes us laugh the most wins.`,
	`The player who can connect the two words in the most creative way wins.`,
	`The player who has the most creative and original interpretation of the word "ultram" and "Iran" when used together, wins.`,
	`The person whose response is most relevant to the prompt wins.`,
	`Player with the most number of words related to transportation wins.`,
	`The player with the most outrageous and believable "fib" wins.`,
	`The player who includes the oldest date in their answer wins.`,
	`The card with the most practical advice wins this round.`,
	`The card that depicts the most positive and effective transformation wins.`,
	`The most creative and realistic ideas will win in this game.`,
	`The card with the most "colorful" and "vivid" description wins.`,
	`The most creative application and use of the word will win in this game.`,
	`The card that best exemplifies the attributes of royalty wins.`,
	`The player whose card describes the most inspiring and enduring impact wins.`,
	`The card with the most creative and scientifically accurate use of "mRNA" wins.`,
	`The most creative and unique use of the words will win in this game.`,
	`The player with the most "relevant" response wins.`,
	`The player with the most "cautionary" or "prepared" response wins.`,
	`The player who can make the most creative and entertaining story using the word "dom" wins.`,
	`The card with the most "high-quality" joke related to the concept of "perspective" wins.`,
	`The most creative and inclusive answer will win in this game.`,
	`Every answer must include a reference to a piece of "equipment". Every answer must mention a "redhead".`,
	`The most creative and unexpected reference to Catholicism wins.`,
	`The most practical or useful answer will win in this game.`,
	`The funniest and most creative use of innuendo wins each round.`,
	`The answer that is closest to the target temperature wins.`,
	`The most humorous and relatable situation will win in this game.`,
	`The card that best portrays a relatable and humorous "struggle" wins.`,
	`The most creative and unexpected use of the word wins.`,
	`The answer that demonstrates the best understanding of the United States' current events and social issues will win in this game.`,
	`The most "innovative" and creative take on the word will win in this game.`,
	`The player with the funniest card related to "Ryan" wins.`,
	`The player who best incorporates musical references wins.`,
	`The most creative and unique interpretation wins.`,
	`The card with the most creative and imaginative use of the word wins.`,
	`The funniest and most creative interpretation wins this round.`,
	`The person who can provide the best argument for safeguarding a single opportunity wins.`,
	`The most creative use of the words in a technological context will win.`,
	`The most "consistent" and coherent answer with the theme wins this game.`,
	`The answer that best incorporates technology and creativity will win.`,
	`The most creative, unique and unexpected combination of categories will win in this game.`,
	`The answer that incorporates the most creative and unique cooking technique wins.`,
	`The best combination of strategic risk-taking and creativity wins.`,
	`The funniest and most creative answer will win in this game.`,
	`The player with the most creative and original justification wins.`,
	`The player with the funniest Canadian-themed manners wins.`,
	`The most imaginative and creative use of the word union to describe a type of restaurant wins.`,
	`The player with the funniest interpretation of a jacket will win.`,
	`The answer that incorporates the concept of a turtle in the most creative way wins!`,
	`The most accurate and precise response will win in this game.`,
	`The most creative and attention-grabbing use of the word "tension" wins.`,
	`The funniest and most inclusive answer will win in this game.`,
	`The card that most creatively incorporates "gravity" wins the round.`,
	`The answer that combines legal knowledge and mathematical precision wins.`
];

export const botNames = [
	`CommerciumPerceptaCorp`,
	`DiscopGBAce`,
	`StartGBPBox`,
	`BrainyGeniusPatch`,
	`Edgeloopsy`,
	`Lesliance Greatance`,
	`EnabliGrillify`,
	`ConvAmplifyQLD`,
	`HebEggViiTech`,
	`PostNexus Upcyclist`,
	`PressFeatherSeptimo`,
	`NailCorderPro`,
	`Fruitionopia`,
	`HeliBeaThingy`,
	`PubliMendPrison`,
	`HemoBooksYield`,
	`ThermorphizeX`,
	`Snolocharter`,
	`BuildvianRoadz`,
	`BlazePox Ventures`,
	`Officer BroChill`,
	`OptiRosarance`,
	`SilentHabitatHQ`,
	`CollectionEugeneX`,
	`RhythmFab`,
	`LegitBuyify`,
	`PerfumSpritzPalooza`,
	`ad bo`,
	`RooftopAlgerythm`,
	`InterpretaAssistaIntro`,
	`PictoPictoPicto`,
	`PhaseMindMapz`,
	`Physizona MotoTronics`,
	`DebatingWealthyFestive`,
	`ExactoGenusTech`,
	`Sushivore Delishery`,
	`PlaneBloggles OxforWebz`,
	`EliminObjectivio`,
	`Supremusicast`,
	`ProgOfficerSageX`,
	`EtiqueSmiEspañol`,
	`TriangulOrbitz`,
	`RicDisclaimerTech`,
	`Grifrox Aerials`,
	`RhythmoCommune`,
	`PodDuoOregenius`,
	`TheozaPizzanomaly`,
	`SynguHonduraRise`,
	`InserPickly`,
	`TerrormudaContestia`,
	`FalseActiProdulgence`,
	`CookiComiGraf`,
	`SeptemFruCorp`,
	`ExplorganMasteries`,
	`FactoCelestiLex`,
	`FlexSnipYesterday`,
	`MetroGlowzity`,
	`SouthernShiftTaxiCo`,
	`Starry Wrapifyz`,
	`MotiBoost ProLeadify`,
	`FortuneReadEats`,
	`ScotContriRalphiq`,
	`Pain-Punch Inc.`,
	`QualiZonix`,
	`BillarChalayera`,
	`Attachium Sportorium`,
	`ShoppyRichuvisor`,
	`Electrolicy`,
	`FeatoExhibitConvict`,
	`CodFury`,
	`FabricHabitatJoy`,
	`AquaSonicity`,
	`Sheethreeminers`,
	`ClaimioHK`,
	`Vocablulariana`,
	`Uni-Netic Connectify`,
	`RebelOutletjerz`,
	`NuSonoRhythm`,
	`Agricanatl`,
	`VeriNTSCRally`,
	`VampiSpotlikeness`,
	`PropoSeektronic`,
	`DislikeGUIfu`,
	`SockNoirItalics`,
	`CorrectoBlitziq`,
	`Tonysa Powertize`,
	`NinjaLinkX`,
	`PrepaSamuQuantico`,
	`StardomSent`,
	`PerceivioBlendify`,
	`HypoDiagnoScan`,
	`ManoRitzyPro`,
	`Assembloport`,
	`VolunTaryVoices`,
	`ShadowVariax`,
	`NewsVaulticus Legallium`,
	`MinimBareCoz`,
	`Complaineur`,
	`CommunalSalsaNet`,
	`DragivOberservey`
];

export const randomTurnPrompt = () => sample(turnPrompts);
export const randomBotPrompt = () => sample(botPrompts);
export const randomAlignerPrompt = () => sample(alignerPrompts);
export const randomBotName = () => sample(botNames);
